In [192]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import linear_model

In [193]:
df = pd.read_csv('insuranceCleanedFinal.csv')
df.head()

   age     sex    bmi  children smoker     region   charges
0   19  female  27.90         0    yes  southwest  16884.92
1   18    male  33.77         1     no  southeast   1725.55
2   28    male  33.00         3     no  southeast   4449.46
3   33    male  22.70         0     no  northwest  21984.47
4   32    male  28.88         0     no  northwest   3866.86

In [194]:
import matplotlib.pyplot as plt
%matplotlib inline

In [195]:
X

      male
0        0
1        1
2        1
3        1
4        1
...    ...
1326     1
1327     0
1328     0
1329     0
1330     0

[1331 rows x 1 columns]

In [196]:
y

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1326    10600.55
1327     2205.98
1328     1629.83
1329     2007.94
1330    29141.36
Name: charges, Length: 1331, dtype: float64

In [197]:
from sklearn.model_selection import train_test_split

In [198]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2)

In [199]:
len(X_train)

1064

In [200]:
len(X_test)

267

In [201]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()

# Train model

In [202]:
clf.fit(X_train,y_train)

LinearRegression()

In [203]:
clf.predict(X_test)

array([13796.07254302, 12071.2832902 , 13796.07254302, 12071.2832902 ,
       13796.07254302, 13796.07254302, 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 12071.2832902 , 13796.07254302,
       12071.2832902 , 12071.2832902 , 12071.2832902 , 12071.2832902 ,
       13796.07254302, 13796.07254302, 13796.07254302, 12071.2832902 ,
       12071.2832902 , 13796.07254302, 12071.2832902 , 13796.07254302,
       13796.07254302, 13796.07254302, 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 13796.07254302, 13796.07254302,
       13796.07254302, 12071.2832902 , 13796.07254302, 13796.07254302,
       12071.2832902 , 12071.2832902 , 12071.2832902 , 12071.2832902 ,
       13796.07254302, 13796.07254302, 12071.2832902 , 13796.07254302,
       12071.2832902 , 12071.2832902 , 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 12071.2832902 , 12071.2832902 ,
       12071.2832902 , 13796.07254302, 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 13796.07254302, 12071.2832902 ,
       13796.07254302, 12071.2832902 , 13796.07254302, 12071.2832902 ,
       12071.2832902 , 12071.2832902 , 13796.07254302, 13796.07254302,
       12071.2832902 , 12071.2832902 , 12071.2832902 , 13796.07254302,
       13796.07254302, 13796.07254302, 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 12071.2832902 , 12071.2832902 ,
       12071.2832902 , 12071.2832902 , 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 13796.07254302, 12071.2832902 ,
       12071.2832902 , 13796.07254302, 13796.07254302, 13796.07254302,
       12071.2832902 , 12071.2832902 , 13796.07254302, 13796.07254302,
       12071.2832902 , 13796.07254302, 12071.2832902 , 12071.2832902 ,
       13796.07254302, 13796.07254302, 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 13796.07254302, 13796.07254302,
       12071.2832902 , 12071.2832902 , 13796.07254302, 13796.07254302,
       13796.07254302, 12071.2832902 , 13796.07254302, 12071.2832902 ,
       12071.2832902 , 13796.07254302, 13796.07254302, 12071.2832902 ,
       12071.2832902 , 12071.2832902 , 13796.07254302, 12071.2832902 ,
       13796.07254302, 12071.2832902 , 12071.2832902 , 12071.2832902 ,
       13796.07254302, 13796.07254302, 12071.2832902 , 12071.2832902 ,
       12071.2832902 , 12071.2832902 , 13796.07254302, 12071.2832902 ,
       13796.07254302, 12071.2832902 , 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 12071.2832902 , 12071.2832902 ,
       13796.07254302, 13796.07254302, 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 12071.2832902 , 12071.2832902 ,
       13796.07254302, 13796.07254302, 13796.07254302, 12071.2832902 ,
       13796.07254302, 13796.07254302, 13796.07254302, 13796.07254302,
       13796.07254302, 13796.07254302, 12071.2832902 , 13796.07254302,
       12071.2832902 , 12071.2832902 , 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 12071.2832902 , 13796.07254302,
       13796.07254302, 13796.07254302, 12071.2832902 , 12071.2832902 ,
       13796.07254302, 13796.07254302, 12071.2832902 , 13796.07254302,
       13796.07254302, 12071.2832902 , 13796.07254302, 13796.07254302,
       13796.07254302, 12071.2832902 , 12071.2832902 , 12071.2832902 ,
       12071.2832902 , 12071.2832902 , 12071.2832902 , 13796.07254302,
       12071.2832902 , 12071.2832902 , 12071.2832902 , 13796.07254302,
       12071.2832902 , 12071.2832902 , 13796.07254302, 13796.07254302,
       12071.2832902 , 13796.07254302, 12071.2832902 , 12071.2832902 ,
       12071.2832902 , 12071.2832902 , 12071.2832902 , 12071.2832902 ,
       13796.07254302, 12071.2832902 , 13796.07254302, 13796.07254302,
       12071.2832902 , 12071.2832902 , 12071.2832902 , 13796.07254302,
       12071.2832902 , 13796.07254302, 13796.07254302, 13796.07254302,
       13796.07254302, 12071.2832902 , 12071.2832902 , 12071.2832902 ,
       13796.07254302, 12071.2832902 , 13796.07254302, 12071.2832902 ,
       13796.07254302, 12071.2832902 , 13796.07254302])

In [204]:
y_test

712     12146.97
1298     2464.62
1066    39871.70
664     40003.33
940     12982.87
          ...
493     17942.11
1329     2007.94
751     17128.43
440     37079.37
775      5934.38
Name: charges, Length: 267, dtype: float64

# Check accuracy of Model

In [205]:
clf.score(X_test, y_test)

-0.00819786029248859

In [206]:
import pandas as pd

In [207]:
sex= pd.read_csv('insuranceCleanedFinal.csv')
ohe_sex = pd.get_dummies(sex[['sex']])
print(ohe_sex.to_string())

      sex_female  sex_male
0              1         0
1              0         1
2              0         1
3              0         1
4              0         1
5              1         0
6              1         0
7              1         0
8              0         1
9              1         0
10             0         1
11             1         0
12             0         1
13             1         0
14             0         1
15             0         1
16             1         0
17             0         1
18             0         1
19             0         1
20             1         0
21             1         0
22             0         1
23             1         0
24             0         1
25             1         0
26             1         0
27             1         0
28             0         1
29             0         1
30             0         1
31             1         0
32             1         0
33             0         1
34             0         1
35             1         0
36             0         1
37             0         1
38             0         1
39             1         0
40             1         0
41             0         1
42             1         0
43             0         1
44             0         1
45             1         0
46             1         0
47             1         0
48             0         1
49             1         0
50             1         0
51             0         1
52             0         1
53             1         0
54             0         1
55             1         0
56             0         1
57             1         0
58             1         0
59             0         1
60             0         1
61             0         1
62             1         0
63             1         0
64             1         0
65             1         0
66             0         1
67             1         0
68             0         1
69             1         0
70             0         1
71             1         0
72             0         1
73             0         1
74             0         1
75             1         0
76             0         1
77             1         0
78             1         0
79             0         1
80             1         0
81             0         1
82             1         0
83             1         0
84             0         1
85             1         0
86             1         0
87             1         0
88             1         0
89             1         0
90             1         0
91             0         1
92             0         1
93             1         0
94             1         0
95             1         0
96             0         1
97             0         1
98             0         1
99             1         0
100            0         1
101            1         0
102            1         0
103            1         0
104            0         1
105            1         0
106            0         1
107            0         1
108            0         1
109            0         1
110            1         0
111            0         1
112            1         0
113            0         1
114            0         1
115            0         1
116            1         0
117            1         0
118            1         0
119            0         1
120            0         1
121            1         0
122            0         1
123            1         0
124            1         0
125            1         0
126            1         0
127            1         0
128            0         1
129            1         0
130            1         0
131            1         0
132            0         1
133            1         0
134            1         0
135            0         1
136            0         1
137            1         0
138            1         0
139            0         1
140            0         1
141            0         1
142            0         1
143            0         1
144            1         0
145            0         1
146            1         0
147            1         0
148            0         1
149            0         1
150            0         1
151            1         0
152            1         0
153            1         0
154            0         1
155            0         1
156            0         1
157            0         1
158            1         0
159            1         0
160            1         0
161            0         1
162            1         0
163            0         1
164            0         1
165            1         0
166            1         0
167            1         0
168            0         1
169            0         1
170            0         1
171            0         1
172            1         0
173            1         0
174            1         0
175            0         1
176            0         1
177            1         0
178            1         0
179            0         1
180            1         0
181            0         1
182            1         0
183            0         1
184            0         1
185            1         0
186            1         0
187            1         0
188            1         0
189            0         1
190            1         0
191            0         1
192            1         0
193            0         1
194            0         1
195            1         0
196            1         0
197            1         0
198            1         0
199            1         0
200            1         0
201            1         0
202            1         0
203            0         1
204            1         0
205            0         1
206            0         1
207            1         0
208            0         1
209            0         1
210            0         1
211            0         1
212            1         0
213            1         0
214            1         0
215            1         0
216            0         1
217            1         0
218            1         0
219            1         0
220            1         0
221            0         1
222            0         1
223            0         1
224            0         1
225            0         1
226            1         0
227            1         0
228            0         1
229            1         0
230            1         0
231            1         0
232            0         1
233            0         1
234            1         0
235            1         0
236            0         1
237            0         1
238            0         1
239            1         0
240            1         0
241            1         0
242            0         1
243            1         0
244            0         1
245            1         0
246            0         1
247            0         1
248            0         1
249            0         1
250            1         0
251            0         1
252            0         1
253            0         1
254            1         0
255            0         1
256            1         0
257            0         1
258            0         1
259            1         0
260            1         0
261            0         1
262            0         1
263            1         0
264            0         1
265            0         1
266            1         0
267            0         1
268            0         1
269            0         1
270            0         1
271            0         1
272            0         1
273            0         1
274            1         0
275            0         1
276            1         0
277            0         1
278            1         0
279            1         0
280            0         1
281            0         1
282            1         0
283            1         0
284            0         1
285            1         0
286            1         0
287            1         0
288            0         1
289            1         0
290            0         1
291            0         1
292            1         0
293            0         1
294            0         1
295            0         1
296            0         1
297            0         1
298            1         0
299            0         1
300            1         0
301            1         0
302            1         0
303            1         0
304            0         1
305            1         0
306            1         0
307            0         1
308            1         0
309            0         1
310            1         0
311            0         1
312            0         1
313            1         0
314            0         1
315            0         1
316            0         1
317            1         0
318            0         1
319            0         1
320            1         0
321            0         1
322            0         1
323            0         1
324            0         1
325            1         0
326            0         1
327            1         0
328            0         1
329            1         0
330            0         1
331            1         0
332            1         0
333            1         0
334            0         1
335            0         1
336            0         1
337            0         1
338            1         0
339            1         0
340            0         1
341            1         0
342            0         1
343            1         0
344            1         0
345            0         1
346            0         1
347            1         0
348            0         1
349            1         0
350            1         0
351            1         0
352            0         1
353            1         0
354            0         1
355            0         1
356            0         1
357            0         1
358            1         0
359            1         0
360            0         1
361            1         0
362            1         0
363            1         0
364            1         0
365            1         0
366            1         0
367            0         1
368            0         1
369            1         0
370            1         0
371            1         0
372            0         1
373            0         1
374            1         0
375            1         0
376            0         1
377            1         0
378            0         1
379            1         0
380            0         1
381            0         1
382            1         0
383            0         1
384            0         1
385            1         0
386            0         1
387            1         0
388            1         0
389            0         1
390            1         0
391            0         1
392            0         1
393            1         0
394            0         1
395            1         0
396            0         1
397            0         1
398            1         0
399            1         0
400            0         1
401            1         0
402            0         1
403            0         1
404            1         0
405            1         0
406            1         0
407            0         1
408            0         1
409            0         1
410            1         0
411            1         0
412            0         1
413            1         0
414            1         0
415            0         1
416            1         0
417            0         1
418            1         0
419            0         1
420            0         1
421            0         1
422            0         1
423            0         1
424            0         1
425            1         0
426            1         0
427            1         0
428            1         0
429            0         1
430            1         0
431            0         1
432            1         0
433            0         1
434            0         1
435            0         1
436            0         1
437            1         0
438            0         1
439            1         0
440            1         0
441            0         1
442            1         0
443            0         1
444            1         0
445            0         1
446            1         0
447            1         0
448            0         1
449            0         1
450            0         1
451            0         1
452            0         1
453            0         1
454            0         1
455            1         0
456            1         0
457            0         1
458            1         0
459            1         0
460            0         1
461            1         0
462            0         1
463            0         1
464            1         0
465            1         0
466            1         0
467            1         0
468            1         0
469            0         1
470            1         0
471            1         0
472            1         0
473            0         1
474            0         1
475            0         1
476            0         1
477            0         1
478            0         1
479            0         1
480            0         1
481            1         0
482            1         0
483            0         1
484            1         0
485            1         0
486            0         1
487            1         0
488            0         1
489            1         0
490            1         0
491            1         0
492            0         1
493            0         1
494            0         1
495            1         0
496            0         1
497            1         0
498            1         0
499            0         1
500            0         1
501            0         1
502            0         1
503            1         0
504            0         1
505            0         1
506            0         1
507            1         0
508            1         0
509            0         1
510            0         1
511            0         1
512            0         1
513            0         1
514            0         1
515            0         1
516            0         1
517            1         0
518            0         1
519            1         0
520            1         0
521            1         0
522            1         0
523            0         1
524            1         0
525            1         0
526            1         0
527            0         1
528            0         1
529            0         1
530            1         0
531            0         1
532            0         1
533            0         1
534            0         1
535            1         0
536            1         0
537            1         0
538            0         1
539            1         0
540            1         0
541            1         0
542            0         1
543            0         1
544            0         1
545            1         0
546            1         0
547            1         0
548            0         1
549            1         0
550            0         1
551            1         0
552            1         0
553            0         1
554            0         1
555            0         1
556            1         0
557            0         1
558            1         0
559            1         0
560            0         1
561            0         1
562            1         0
563            1         0
564            1         0
565            0         1
566            1         0
567            0         1
568            1         0
569            1         0
570            1         0
571            1         0
572            1         0
573            1         0
574            0         1
575            0         1
576            1         0
577            0         1
578            0         1
579            0         1
580            1         0
581            0         1
582            1         0
583            0         1
584            1         0
585            1         0
586            1         0
587            1         0
588            0         1
589            0         1
590            1         0
591            0         1
592            1         0
593            1         0
594            1         0
595            0         1
596            1         0
597            1         0
598            0         1
599            1         0
600            1         0
601            1         0
602            1         0
603            1         0
604            1         0
605            0         1
606            0         1
607            1         0
608            1         0
609            1         0
610            1         0
611            1         0
612            1         0
613            1         0
614            0         1
615            1         0
616            1         0
617            0         1
618            0         1
619            1         0
620            0         1
621            0         1
622            1         0
623            0         1
624            0         1
625            0         1
626            1         0
627            0         1
628            0         1
629            1         0
630            0         1
631            0         1
632            0         1
633            1         0
634            1         0
635            0         1
636            0         1
637            0         1
638            0         1
639            0         1
640            1         0
641            0         1
642            0         1
643            0         1
644            1         0
645            0         1
646            1         0
647            1         0
648            1         0
649            1         0
650            1         0
651            1         0
652            1         0
653            1         0
654            0         1
655            1         0
656            1         0
657            0         1
658            1         0
659            1         0
660            0         1
661            1         0
662            0         1
663            0         1
664            1         0
665            0         1
666            1         0
667            0         1
668            1         0
669            0         1
670            1         0
671            1         0
672            0         1
673            1         0
674            0         1
675            0         1
676            1         0
677            1         0
678            0         1
679            0         1
680            0         1
681            1         0
682            0         1
683            0         1
684            0         1
685            1         0
686            0         1
687            0         1
688            0         1
689            0         1
690            0         1
691            1         0
692            1         0
693            1         0
694            0         1
695            0         1
696            1         0
697            1         0
698            1         0
699            0         1
700            1         0
701            1         0
702            1         0
703            1         0
704            0         1
705            1         0
706            1         0
707            0         1
708            1         0
709            1         0
710            0         1
711            1         0
712            0         1
713            1         0
714            0         1
715            1         0
716            1         0
717            1         0
718            0         1
719            0         1
720            0         1
721            1         0
722            1         0
723            0         1
724            1         0
725            1         0
726            1         0
727            0         1
728            0         1
729            1         0
730            1         0
731            1         0
732            1         0
733            1         0
734            0         1
735            0         1
736            0         1
737            0         1
738            0         1

In [208]:
dummies = pd.get_dummies(df.sex)
dummies

      female  male
0          1     0
1          0     1
2          0     1
3          0     1
4          0     1
...      ...   ...
1326       0     1
1327       1     0
1328       1     0
1329       1     0
1330       1     0

[1331 rows x 2 columns]

In [209]:
merged = pd.concat([df,dummies],axis='columns')
merged

      age     sex    bmi  children smoker     region   charges  female  male
0      19  female  27.90         0    yes  southwest  16884.92       1     0
1      18    male  33.77         1     no  southeast   1725.55       0     1
2      28    male  33.00         3     no  southeast   4449.46       0     1
3      33    male  22.70         0     no  northwest  21984.47       0     1
4      32    male  28.88         0     no  northwest   3866.86       0     1
...   ...     ...    ...       ...    ...        ...       ...     ...   ...
1326   50    male  30.97         3     no  northwest  10600.55       0     1
1327   18  female  31.92         0     no  northeast   2205.98       1     0
1328   18  female  36.85         0     no  southeast   1629.83       1     0
1329   21  female  25.80         0     no  southwest   2007.94       1     0
1330   61  female  29.07         0    yes  northwest  29141.36       1     0

[1331 rows x 9 columns]

In [210]:
final = merged.drop(['sex','female','age','bmi','smoker','region','children'], axis = 'columns')
final

       charges  male
0     16884.92     0
1      1725.55     1
2      4449.46     1
3     21984.47     1
4      3866.86     1
...        ...   ...
1326  10600.55     1
1327   2205.98     0
1328   1629.83     0
1329   2007.94     0
1330  29141.36     0

[1331 rows x 2 columns]

In [211]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [212]:
X= final.drop('charges', axis='columns')

In [213]:
X

      male
0        0
1        1
2        1
3        1
4        1
...    ...
1326     1
1327     0
1328     0
1329     0
1330     0

[1331 rows x 1 columns]

In [214]:
y = final.charges 
y

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1326    10600.55
1327     2205.98
1328     1629.83
1329     2007.94
1330    29141.36
Name: charges, Length: 1331, dtype: float64

In [215]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X,y, test_size= 0.2, random_state =1)

In [216]:
Xtest

      male
1258     0
325      0
930      1
1020     0
1154     0
...    ...
8        1
241      0
283      0
315      1
452      1

[267 rows x 1 columns]

In [217]:
ytest

1258    10370.91
325      3561.89
930      4673.39
1020     8569.86
1154     3989.84
          ...
8        6406.41
241     35160.13
283      9625.92
315      8835.26
452      1769.53
Name: charges, Length: 267, dtype: float64

In [218]:
model.fit(Xtrain,ytrain)

LinearRegression()

In [219]:
print(model.score(Xtest,ytest))
print("Model coefficients:", model.coef_)
print("Model intercept:", model.intercept_)

0.0012257999418274768
Model coefficients: [985.17767364]
Model intercept: 12732.162730769232

In [220]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [221]:
y_pred = model.predict(Xtest)

In [222]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)

Mean Squared Error (MSE): 147801577.31970033
Mean Absolute Error (MAE): 9275.296745538664